development:
  adapter: postgresql
  encoding: utf8
  database: project_development
  pool: 5
  username: fatimawilliams
  password:
  timeout: 5000

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: project_test
  pool: 5
  username: fatimawilliams
  password:
  timeout: 5000

production:
  adapter: postgresql
  encoding: utf8
  database: project_production
  pool: 5
  username:
  password:
  timeout: 5000
